### ISSUE TITLE
EUW is unable to discover streams upon creating a branch mapping

### ISSUE THREAD

**Issue by MarkusRistich** [TheThirdFloor/UnrealP4Migrate#1]
When creating a branch mapping, the UI resets, but the Stream Options are blanked out, despite the checkboxes (which operate like radio buttons) being selected. 

Steps to reproduce:
Create two Streams (//A) and (//B), both children from (//main)
Select "All Streams"
Select one of the valid Target Streams
Select an asset in the Content Browser
Click "Gather Dependencies for Selected Assets"
Click "Create Branch Mapping"

The UI will reset, and the "All Streams" radio button will be selected, but the Target Stream field will be blank, and no options will be presented.

Possible Fix:

On submission, the Stream Option might be reset to "Child Streams", but the radio button does not represent the state.

**Comment by MarkusRistich** [comment]
After resetting we are calling `Initialize`. 
![image](https://user-images.githubusercontent.com/58960741/207233671-9546396b-02bb-4c9c-a6f9-ebe3d512d667.png)

`Initialize` will populate the **Child** stream by default but it won't actually trigger the `OnCheckStateChanged` event, which leaves the UI without the correct radio button selection.

![image](https://user-images.githubusercontent.com/58960741/207233818-2859b6bc-cce8-4fb3-a91d-e4f10668b0a7.png)

Could we instead check the value in `GetStreamSelection`, and if it's null then we set the **Child** stream on initialize?

**Comment by johnsonthomassonttf** [comment]
Addressed in Release 1.1.0
